name: Build TimeTracker

on: [push]

jobs:
    build-windows:
        runs-on: windows-2019

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Setup devcmd
              uses: ilammy/msvc-dev-cmd@v1

            - name: Install Qt
              uses: jurplel/install-qt-action@v3
              with:
                  version: 6.3.1

            - name: Build Qt
              run: |
                  cmake -B build -DCMAKE_PREFIX_PATH=$Qt6_DIR
                  cmake --build build --config Release

            - name: Prepare
              run: |
                  mkdir deployment
                  mv build/Release/TimeTracker.exe deployment/
                  mv build/images deployment/
                  cd deployment
                  windeployqt TimeTracker.exe --release --no-compiler-runtime --no-translations --no-opengl-sw
                  pushd "${{ github.workspace }}\scripts"
                  build-setup-win.bat
              shell: cmd

            - name: Upload build artifacts
              uses: actions/upload-artifact@v3
              with:
                  name: TimeTracker-Windows
                  path: TimeTracker-Installer*.exe

    build-linux:
        runs-on: ubuntu-20.04

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Install Dependencies
              run: |
                  sudo apt update
                  sudo apt install cmake libxss-dev libx11-dev libnotify-dev libglib2.0-dev

            - name: Setup ccache
              uses: Chocobo1/setup-ccache-action@v1
              with:
                  update_packager_index: false
                  ccache_options: |
                      max_size=2G

            - name: Install Qt
              uses: jurplel/install-qt-action@v3
              with:
                  version: 6.3.1

            - name: Build Qt
              run: |
                  cmake -B build -DCMAKE_PREFIX_PATH=$Qt6_DIR
                  cmake --build build

            - name: Prepare build artifcats
              run: |
                  mkdir upload
                  mv build/TimeTracker upload

            - name: Build AppImage
              run: |
                  chmod a+x scripts/build-app-image.sh
                  ./scripts/build-app-image.sh

            - name: Upload build artifacts
              uses: actions/upload-artifact@v3
              with:
                  name: TimeTracker-Linux
                  path: upload
