name: Build TimeTracker

on: [push]

jobs:
    build-windows:
        runs-on: windows-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Setup devcmd
              uses: ilammy/msvc-dev-cmd@v1

            - name: Install Qt
              uses: jurplel/install-qt-action@v3
              with:
                  version: 6.3.1

            - name: Build Qt
              run: |
                  cmake -B build -DCMAKE_PREFIX_PATH=$Qt6_DIR
                  cmake --build build --config Release

            - name: Prepare
              run: |
                  mkdir deployment
                  mv build/Release/TimeTracker.exe deployment/
                  mv build/images deployment/
                  cd deployment
                  windeployqt TimeTracker.exe

            - name: Upload build artifacts
              uses: actions/upload-artifact@v3
              with:
                  name: TimeTracker-Windows
                  path: deployment
